In [17]:
import numpy as np
import math as math
a = np.array([1,2,3])
np.cumprod(a)

array([1, 2, 6])

In [15]:
daily_price = np.array([100,150,160])
daily_returns = np.diff(daily_price)
daily_returns

array([50, 10])

In [16]:
annual_return = np.cumprod(daily_returns+1) - 1
annual_return

array([ 50, 560])

In [53]:
portfolio_as_of_2002 = 100
portfolio_as_of_2012 = 200
years = 0.1 #1/10
#portfolio_as_of_2012 = portfolio_as_of_2002 × (1 + CAGR) ^ 10
annual_return = portfolio_as_of_2012 / portfolio_as_of_2002
print annual_return
CAGR = (math.pow(annuannual_return = portfolio_as_of_2016 / portfolio_as_of_2017
print annual_return
CAGR = (math.pow(annual_return,1) -1) * 100
CAGRal_return,years) -1) * 100
CAGR

2


7.177346253629313

In [62]:
portfolio_as_of_2016 = 335501.18
portfolio_as_of_2017 = 593237.25
years = 1 #1/10
#portfolio_as_of_2012 = portfolio_as_of_2002 × (1 + CAGR) ^ 10
annual_return = portfolio_as_of_2017 / portfolio_as_of_2016
print annual_return
CAGR = (math.pow(annual_return,1) -1) * 100
CAGR

1.7682121118


76.82121118024085

In [60]:
#Rule of 72
CAGR = 12
years_to_double = 72 / CAGR
years_to_double

6

In [64]:
price_in_2014 = 96.15
price_in_2017 = 1110.10
years = 3
annual_return = price_in_2017 / price_in_2014
print annual_return
CAGR = (math.pow(annual_return,1) -1) * 100
CAGR

11.5455018201


1054.55018200728